services:
  postgres:
    image: postgres:latest
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_DB: db_livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/c/docker-volumes/postgres-db:/var/lib/postgresql/db"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: