INSERT INTO tbl_genders (gender_name) VALUES  ('Programação');
INSERT INTO tbl_genders (gender_name) VALUES  ('Banco de Dados');
INSERT INTO tbl_genders (gender_name) VALUES  ('Redes');
INSERT INTO tbl_genders (gender_name) VALUES  ('Segurança da Informação');
INSERT INTO tbl_genders (gender_name) VALUES  ('Engenharia de Software');

INSERT INTO tbl_publishers (publisher_name, publisher_mail) VALUES ('Casa do Código', 'contato@casadocodigo.com.br');
INSERT INTO tbl_publishers (publisher_name, publisher_mail) VALUES ('O''Reilly Media', 'info@oreilly.com');
INSERT INTO tbl_publishers (publisher_name, publisher_mail) VALUES  ('Packt Publishing', 'support@packtpub.com');
INSERT INTO tbl_publishers (publisher_name, publisher_mail) VALUES  ('Apress', 'contact@apress.com');
INSERT INTO tbl_publishers (publisher_name, publisher_mail) VALUES  ('Novatec', 'atendimento@novatec.com.br');

INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Robert C. Martin', 'unclebob@clean.com', '1952-12-05', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Martin Fowler', 'fowler@refactor.com', '1963-01-18', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Eric Evans', 'evans@ddd.com', '1969-08-20', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Brian Goetz', 'goetz@java.com', '1970-06-05', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Andrew S. Tanenbaum', 'tanenbaum@redes.com', '1944-03-16', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Bruce Schneier', 'schneier@security.com', '1963-01-15', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('George Reese', 'reese@cloud.com', '1972-11-11', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Joshua Bloch', 'bloch@java.com', '1961-08-28', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Herbert Schildt', 'schildt@csharp.com', '1951-09-01', NULL);
INSERT INTO tbl_authors (author_name, author_mail, birth_date, date_death) VALUES  ('Mark Richards', 'mark@microservices.com', '1975-07-07', NULL);

INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-1', 'Clean Code', 'Boas práticas de programação', 2008, 464, 1, 1, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-2', 'Clean Architecture', 'Estruturas sustentáveis de software', 2017, 432, 1, 1, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-3', 'Refactoring', 'Melhorando o design de código existente', 2018, 448, 2, 2, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-4', 'Patterns of Enterprise Application Architecture', 'Padrões para aplicações corporativas', 2002, 533, 2, 2, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-5', 'Domain-Driven Design', 'Resolva problemas de software complexos com DDD', 2003, 560, 3, 3, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-6', 'Java Concurrency in Practice', 'Concorrência em Java', 2006, 384, 4, 4, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-7', 'Computer Networks', 'Redes de computadores', 2010, 960, 5, 2, 3, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-8', 'Modern Operating Systems', 'Sistemas Operacionais Modernos', 2014, 1136, 5, 2, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-1-9', 'Applied Cryptography', 'Protocolos, algoritmos e código fonte em C', 1996, 758, 6, 4, 4, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-0', 'Secrets and Lies', 'Digital Security in a Networked World', 2000, 432, 6, 4, 4, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-1', 'Cloud Application Architectures', 'Projetando apps para nuvem', 2009, 264, 7, 2, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-2', 'Effective Java', 'Melhores práticas para Java', 2018, 416, 8, 3, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-3', 'Java Puzzlers', 'Armadilhas para programadores Java', 2005, 384, 8, 3, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-4', 'C# The Complete Reference', 'Referência completa de C#', 2010, 1056, 9, 5, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-5', 'Java: The Complete Reference', 'Referência completa de Java', 2018, 1248, 9, 5, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-6', 'Fundamentals of Software Architecture', 'Fundamentos da arquitetura de software', 2020, 432, 10, 1, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-7', 'Software Architecture Patterns', 'Padrões de arquitetura de software', 2015, 50, 10, 1, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-8', 'Microservices Patterns', 'Padrões para microsserviços', 2019, 520, 10, 1, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-2-9', 'Building Microservices', 'Projetando sistemas distribuídos', 2021, 450, 10, 1, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-0', 'Network Security Essentials', 'Conceitos e aplicações', 2013, 312, 6, 4, 4, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-1', 'Designing Data-Intensive Applications', 'Design de apps orientadas a dados', 2017, 616, 2, 2, 2, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-2', 'Linux Pocket Guide', 'Guia rápido de Linux', 2017, 230, 5, 2, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-3', 'Hands-On Network Programming with Java', 'Redes com Java', 2018, 458, 4, 4, 3, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-4', 'Security Engineering', 'Engenharia de segurança', 2020, 1024, 6, 4, 4, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-5', 'PostgreSQL: Up and Running', 'PostgreSQL para devs', 2014, 256, 7, 2, 2, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-6', 'Learning SQL', 'Aprendendo SQL do zero', 2019, 408, 3, 1, 2, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-7', 'Spring in Action', 'Desenvolvimento com Spring Framework', 2022, 520, 1, 1, 1, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-8', 'Kubernetes Up & Running', 'Gerenciando containers com K8s', 2022, 380, 7, 2, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-3-9', 'The DevOps Handbook', 'Guia de práticas DevOps', 2016, 480, 2, 3, 5, NOW());
INSERT INTO tbl_books (isbn_number, book_title, book_description, age_publish, number_pages, author_id, publisher_id, gender_id, registration_date) VALUES ('978-4-0', 'CI/CD with Jenkins', 'Integração e entrega contínuas com Jenkins', 2021, 352, 3, 1, 5, NOW());
